var hierarchy =
[
    [ "AvailableInstructions", "class_available_instructions.html", null ],
    [ "EditorObject", "class_editor_object.html", null ],
    [ "Block.EffectReaction", "class_block_1_1_effect_reaction.html", null ],
    [ "IDisposable", null, [
      [ "Subscription< Tmessage >", "class_subscription.html", null ]
    ] ],
    [ "InteractibleParameters", "class_interactible_parameters.html", null ],
    [ "LevelData", "class_level_data.html", null ],
    [ "MessageWarehouse", "class_message_warehouse.html", null ],
    [ "MonoBehaviour", null, [
      [ "ArrowAnim", "class_arrow_anim.html", null ],
      [ "BlockExploder", "class_block_exploder.html", null ],
      [ "ButtonCounterScript", "class_button_counter_script.html", null ],
      [ "CameraMsgs", "class_camera_msgs.html", null ],
      [ "Character", "class_character.html", [
        [ "BigCharacter", "class_big_character.html", null ],
        [ "MiniCharacter", "class_mini_character.html", null ]
      ] ],
      [ "ConditionCard", "class_condition_card.html", null ],
      [ "ConditionCardFrame", "class_condition_card_frame.html", null ],
      [ "ConditionCardPicker", "class_condition_card_picker.html", null ],
      [ "Counter", "class_counter.html", null ],
      [ "EditorInstructionButton", "class_editor_instruction_button.html", null ],
      [ "EditorLogic", "class_editor_logic.html", null ],
      [ "EditorMenuButton", "class_editor_menu_button.html", null ],
      [ "EditorSaveButton", "class_editor_save_button.html", null ],
      [ "EditorSurface", "class_editor_surface.html", null ],
      [ "EditorSurfacePoint", "class_editor_surface_point.html", null ],
      [ "EditorTool", "class_editor_tool.html", null ],
      [ "EditorToolFeedback", "class_editor_tool_feedback.html", null ],
      [ "EventAggregator", "class_event_aggregator.html", null ],
      [ "FaceCamera", "class_face_camera.html", null ],
      [ "FindingSpaceSign", "class_finding_space_sign.html", null ],
      [ "GameLogic", "class_game_logic.html", null ],
      [ "GenericButton", "class_generic_button.html", null ],
      [ "Interactible", "class_interactible.html", null ],
      [ "LevelButtons", "class_level_buttons.html", null ],
      [ "LevelObject", "class_level_object.html", [
        [ "Block", "class_block.html", null ],
        [ "Item", "class_item.html", null ]
      ] ],
      [ "LevelObjectFactory", "class_level_object_factory.html", null ],
      [ "LoopCounter", "class_loop_counter.html", null ],
      [ "MainMenuLogic", "class_main_menu_logic.html", null ],
      [ "MapContainer", "class_map_container.html", null ],
      [ "MapController", "class_map_controller.html", null ],
      [ "MapMenuLogic", "class_map_menu_logic.html", null ],
      [ "MapRenderer", "class_map_renderer.html", null ],
      [ "MessageScreen", "class_message_screen.html", null ],
      [ "MessageScreenButton", "class_message_screen_button.html", null ],
      [ "MessageScreenManager", "class_message_screen_manager.html", null ],
      [ "MoveCursor", "class_move_cursor.html", null ],
      [ "PathContainer", "class_path_container.html", null ],
      [ "PathPoint", "class_path_point.html", null ],
      [ "Placeable", "class_placeable.html", null ],
      [ "Road", "class_road.html", [
        [ "ConnectorDouble", "class_connector_double.html", null ],
        [ "ConnectorVertical", "class_connector_vertical.html", null ],
        [ "NodeIfIn", "class_node_if_in.html", null ],
        [ "NodeIfOut", "class_node_if_out.html", null ],
        [ "NodeLoopIn", "class_node_loop_in.html", null ],
        [ "NodeLoopOut", "class_node_loop_out.html", null ],
        [ "NodeVerticalButton", "class_node_vertical_button.html", null ]
      ] ],
      [ "RoadButton", "class_road_button.html", null ],
      [ "RoadFactory", "class_road_factory.html", null ],
      [ "RoadIO", "class_road_i_o.html", [
        [ "RoadInput", "class_road_input.html", null ],
        [ "RoadOutput", "class_road_output.html", null ]
      ] ],
      [ "RoadMovementLogic", "class_road_movement_logic.html", null ],
      [ "RoadPlacementLogic", "class_road_placement_logic.html", null ],
      [ "ScrollTexture", "class_scroll_texture.html", null ],
      [ "SelectArrow", "class_select_arrow.html", null ],
      [ "SelectedOutputMarker", "class_selected_output_marker.html", null ],
      [ "SoundEngine", "class_sound_engine.html", null ],
      [ "VerticalButton", "class_vertical_button.html", null ]
    ] ],
    [ "MsgBigCharacterAllActionsFinished", "class_msg_big_character_all_actions_finished.html", null ],
    [ "MsgBigRobotAction", "class_msg_big_robot_action.html", null ],
    [ "MsgBigRobotIdle", "class_msg_big_robot_idle.html", null ],
    [ "MsgBlockLength", "class_msg_block_length.html", null ],
    [ "MsgDisableAllButtons", "class_msg_disable_all_buttons.html", null ],
    [ "MsgEditorAvailableInstructionsChanged", "class_msg_editor_available_instructions_changed.html", null ],
    [ "MsgEditorMapSize", "class_msg_editor_map_size.html", null ],
    [ "MsgEditorMenu", "class_msg_editor_menu.html", null ],
    [ "MsgEditorResetAllCounters", "class_msg_editor_reset_all_counters.html", null ],
    [ "MsgEditorSaveMap", "class_msg_editor_save_map.html", null ],
    [ "MsgEditorSurfaceTapped", "class_msg_editor_surface_tapped.html", null ],
    [ "MsgEditorToolSelected", "class_msg_editor_tool_selected.html", null ],
    [ "MsgEnableAllButtons", "class_msg_enable_all_buttons.html", null ],
    [ "MsgEnableButton", "class_msg_enable_button.html", null ],
    [ "MsgFindingSpace", "class_msg_finding_space.html", null ],
    [ "MsgGetMainCameraTransform", "class_msg_get_main_camera_transform.html", null ],
    [ "MsgHideAllScreens", "class_msg_hide_all_screens.html", null ],
    [ "MsgPlaceCharacter", "class_msg_place_character.html", null ],
    [ "MsgPlaySfx", "class_msg_play_sfx.html", null ],
    [ "MsgPlaySfxAtPoint", "class_msg_play_sfx_at_point.html", null ],
    [ "MsgRenderMainCharacter", "class_msg_render_main_character.html", null ],
    [ "MsgRenderMapAndItems", "class_msg_render_map_and_items.html", null ],
    [ "MsgResetEditorSurface", "class_msg_reset_editor_surface.html", null ],
    [ "MsgSetAvInstructions", "class_msg_set_av_instructions.html", null ],
    [ "MsgShowScreen", "class_msg_show_screen.html", null ],
    [ "MsgSomethingTapped", "class_msg_something_tapped.html", null ],
    [ "MsgStartRoadMovement", "class_msg_start_road_movement.html", null ],
    [ "MsgStopMovement", "class_msg_stop_movement.html", null ],
    [ "MsgTakeItem", "class_msg_take_item.html", null ],
    [ "MsgUseItem", "class_msg_use_item.html", null ],
    [ "PathContainer.Path", "struct_path_container_1_1_path.html", null ],
    [ "PropertyAttribute", null, [
      [ "UniqueIdentifierAttribute", "class_unique_identifier_attribute.html", null ]
    ] ],
    [ "ResponseWrapper< TPetition, TResponse >", "class_response_wrapper.html", null ],
    [ "RoadPlacementLogic.RoadChanges", "class_road_placement_logic_1_1_road_changes.html", null ],
    [ "EditorLogic.SelectedTool", "class_editor_logic_1_1_selected_tool.html", null ],
    [ "Singleton", null, [
      [ "InteractibleManager", "class_interactible_manager.html", null ],
      [ "PlaySpaceManager", "class_play_space_manager.html", null ],
      [ "SpaceCollectionManager", "class_space_collection_manager.html", null ]
    ] ]
];